# Generated by Django 6.0.2 on 2026-03-28 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='owner',
        ),
    ]
